### ISSUE TITLE
Duplicación de opciones 

### ISSUE THREAD

**Issue by jsuarezl** [fisalazarm/DuocAPP#11]
En "sección" la opciones se encuentran duplicadas, adjunto una imagen de ejemplo
![image](https://user-images.githubusercontent.com/22179346/115329051-afe64180-a15f-11eb-90ce-8ad07fae295d.png)

**Comment by fisalazarm** [comment]
Se muestra así ya que en la base de datos entregada, están duplicado por sus secciones
