### ISSUE TITLE
Contraseñas no encriptadas ni ocultas

### ISSUE THREAD

**Issue by jsuarezl** [fisalazarm/DuocAPP#8]
Al momento de listar datos de usuario, se listan las contraseñas sin encriptar ni tampoco se dejan ocultas. Se recomienda encriptar y ocultar las contraseñas por seguridad

**Comment by fisalazarm** [comment]
Las contraseñas en la tabla están encriptadas, así que no hay problema.

**Comment by fisalazarm** [comment]
Ahora no se muestra la contraseña en la tabla
